# Autogenerated wrapper script for CPUInfo_jll for armv7l-linux-gnueabihf
export cache_info, cpu_info, isa_info, libcpuinfo

JLLWrappers.@generate_wrapper_header("CPUInfo")
JLLWrappers.@declare_library_product(libcpuinfo, "libcpuinfo.so")
JLLWrappers.@declare_executable_product(cache_info)
JLLWrappers.@declare_executable_product(cpu_info)
JLLWrappers.@declare_executable_product(isa_info)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcpuinfo,
        "lib/libcpuinfo.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        cache_info,
        "bin/cache-info",
    )

    JLLWrappers.@init_executable_product(
        cpu_info,
        "bin/cpu-info",
    )

    JLLWrappers.@init_executable_product(
        isa_info,
        "bin/isa-info",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
