# Autogenerated wrapper script for CPUInfo_jll for x86_64-w64-mingw32
export cache_info, cpu_info, isa_info, libcpuinfo

JLLWrappers.@generate_wrapper_header("CPUInfo")
JLLWrappers.@declare_library_product(libcpuinfo, "libcpuinfo.dll")
JLLWrappers.@declare_executable_product(cache_info)
JLLWrappers.@declare_executable_product(cpu_info)
JLLWrappers.@declare_executable_product(isa_info)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcpuinfo,
        "bin\\libcpuinfo.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        cache_info,
        "bin\\cache-info.exe",
    )

    JLLWrappers.@init_executable_product(
        cpu_info,
        "bin\\cpu-info.exe",
    )

    JLLWrappers.@init_executable_product(
        isa_info,
        "bin\\isa-info.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
