# Autogenerated wrapper script for CPUInfo_jll for x86_64-w64-mingw32
export libcpuinfo

JLLWrappers.@generate_wrapper_header("CPUInfo")
JLLWrappers.@declare_library_product(libcpuinfo, "libcpuinfo.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcpuinfo,
        "bin\\libcpuinfo.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
